imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_snappy:  
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
        options:
            - { name: 'viewport-size', value: ‘1024x768’ }
            - { name: 'page-size', value: 'A4' }
            - { name: 'encoding', value: 'UTF8' }

easy_admin:
    list:
        # expanded configuration format
#        actions:
#            - { name: '-edit'}
#            - { name: 'modificar', label: 'Modificar' }
    entities:
        Producto:
            class: Trinity\LibuBundle\Entity\Producto
            label: 'Productos'
            form: 
                fields:
                    - { type: 'group', css_class: 'col-sm-6'}
                    - { property: 'codigo', label: 'Producto', help: 'Máximo 20 caracteres', type_options: { trim: true } }
                    - { property: 'vendedor', label: 'Vendedor', help: 'Máximo 20 caracteres', type_options: { trim: true } }
                    - { property: 'precio', label: 'Precio', type_options: { trim: true } }
                    - { property: 'activo', label: '¿Activo?', type: 'choice', type_options: { trim: true, choices: {si: 'si', no: 'no'} } }
            list: 
                title: 'Lista de productos en venta'
                fields: [{ property: 'Codigo', label:'Producto'}, 'Vendedor', 'Precio', 'Activo']

   #     - LibuBundle\Entity\Tematica
    #    - LibuBundle\Entity\Responsable
     #   - LibuBundle\Entity\ProductoVendido
      #  - LibuBundle\Entity\Tipo
      #  Venta: 
       #     class: Trinity\LibuBundle\Entity\Venta
    site_name: 'Trinity Admin'
    design:
        brand_color: 'red'
        color_scheme: 'light'
        menu:
            - Producto 

            - { label: 'Crear Producto', url: 'http://localhost/Libu/web/app.php/libu/producto' }
            - { label: 'Volver a Venta', url: 'http://localhost/Libu/web/app.php/libu/venta' }


