# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    serializer.normalizer:
        class: 		Symfony\Component\Serializer\Serializer
#    service_name:
#        class: Trinity\LibuBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form_login_authenticator:
        class: Trinity\LibuBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]

    app.books:
        class: Trinity\LibuBundle\Books\BookManager
        arguments: [ "@doctrine.orm.entity_manager", "@validator", "%mailer_user%", "%mailer_password%" ]
