<?php

namespace Trinity\LibuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalisisRepository extends \Doctrine\ORM\EntityRepository
{

    /*
    *  Obtiene los resultados del análisis para determinado código
    */

    public function buscaCrawled($codigo)
    {
        $parameters = array( 
            'codigo' => $codigo,
        );
        $query = $this->getEntityManager()->createQuery(
            'SELECT a
            FROM LibuBundle:Analisis a
            WHERE a.codigo = :codigo'
        )->setParameters($parameters);
        
        $crawled  = $query->getResult();  
        return $crawled;          
    }

}
