<?php

namespace Trinity\LibuBundle\Repository;

/**
 * ClienteFacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteFacturaRepository extends \Doctrine\ORM\EntityRepository
{
}
