<?php

namespace Trinity\LibuBundle\Repository;

/**
 * ConservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConservacionRepository extends \Doctrine\ORM\EntityRepository
{
}
