<?php

namespace Trinity\LibuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibroRepository extends EntityRepository
{
	/*
	*  Obtiene libros
	*/
    public function buscaLibros($limit = 10)
    {
        $sql = 
            "SELECT isbn
            FROM libro 
            WHERE estatus = 'AGIL'
            LIMIT ".$limit
        ;
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();           
    }


    /*
    *  Obtiene el código del último libro subido
    */
    public function mayorCodigo()
    {
        $sql = 
            "SELECT codigo
            FROM libro 
            ORDER BY codigo DESC
            LIMIT 1"
        ;
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();           
    }


}
