<?php

namespace Trinity\LibuBundle\Repository;

/**
 * TipolibroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipolibroRepository extends \Doctrine\ORM\EntityRepository
{
}
